// <auto-generated />
using ClassLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary.Migrations
{
    [DbContext(typeof(AdatContext))]
    [Migration("20240325133317_Embik")]
    partial class Embik
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClassLibrary.Models.Nyilvantartas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Eletkor")
                        .HasColumnType("int");

                    b.Property<string>("Erdeklodes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Foglalkozas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nemzetiseg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Nyilvantartasok");
                });
#pragma warning restore 612, 618
        }
    }
}
